version: "3.9"
services:
  
  api:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "orders_api_db"
